### ISSUE TITLE
cleanup: strip out chunks with [music] only, and other small chunks during indexing

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/philosophize-this#7]
Example:
<img width="899" alt="image" src="https://github.com/devflowinc/philosophize-this/assets/6070690/1faaa6de-548f-42fe-9f61-96dc5aefcee8">

**Comment by skeptrunedev** [comment]
https://github.com/devflowinc/philosophize-this/blob/main/transcript-scrape/bulkCreate.js#L5

To complete this issue, in `bulkCreate.js`, remove chunks from the array which are less than 5 words.
